pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage ("AWS Creds") {
            steps {
                withCredentials([[
                $class: 'AmazonWebServicesCredentialsBinding',
                credentialsId: 'demo',
                accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]])
            }
        }

        stage ("terraform init") {
            steps {
                sh '''
                cd AWS-Terraform/WebServer
                ls -l
                terraform init
                '''
            }
        }
        
        stage ("plan") {
            steps {
                sh '''
                cd AWS-Terraform/WebServer
                ls -l
                terraform plan
                '''
            }
        }

        stage ("Action") {
            steps {
                sh '''
                export AWS_PROFILE=${profile}
                echo "Terraform action is --> ${action}"
                cd AWS-Terraform/WebServer
                ls -l
                terraform ${action} -auto-approve
                '''
           }
        }
    }
}
    
