pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('docker-server') {
            steps {
              sh '''
              cd development/DockerBuild
              whoami
              ls -l
              docker build -t demo-app:1.0.0 .
              docker image ls
              docker push demo-app:1.0.0
              '''
            }
        }     
    }
}

