pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
    
        stage ("terraform init") {
            steps {
                sh '''
                cd AWS-Terraform
                ls -l
                terraform init
                '''
            }
        }
        
        stage ("plan") {
            steps {
                sh ('terraform plan') 
            }
        }

        stage ("Action") {
            steps {
                echo "Terraform action is --> ${action}"
                sh ('terraform ${action} -auto-approve -var="access_key=${access_key}" -var="secret_access_key=${secret_access_key}"') 
           }
        }
    }
}
    
