apiVersion: v1
kind: Service
metadata:
  name: lb-bluegreen-test
  labels:
    app: bluegreen-test
    color: green
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bluegreen-test
    color: green